name       : acsccid
version    : 1.1.4
release    : 1
source     :
    - https://netcologne.dl.sourceforge.net/project/acsccid/acsccid/1.1.4/acsccid-1.1.4.tar.bz2 : 1607591ee0df07c0157a71f6cb61e1e11fe1fa17331f02d2dff020db0e28c0ae
license    : LGPL-2.1
component  : security.library
summary    : ACS CCID PC/SC Driver
description: |
    acsccid is a PC/SC driver for Linux/Mac OS X and it supports ACS CCID smart card readers. This library provides a PC/SC IFD handler implementation and communicates with the readers through the PC/SC Lite resource manager (pcscd).
builddeps  :
    - pkgconfig(libusb-1.0) 
    - pkgconfig(libpcsclite)
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
    install -Dm644 src/92_pcscd_acsccid.rules $installdir%libdir%/udev/rules.d/92_pcscd_acsccid.rules
