name       : acsccid
version    : 1.1.8
release    : 6
source     :
    - https://github.com/acshk/acsccid/archive/v1.1.8.tar.gz : 68d15eb20e7f52153509f1dc300cf0c68b388c59d7d124ba494fd96c61a6e7c6
license    : LGPL-2.1-or-later
component  : security.library
summary    : ACS CCID PC/SC Driver
description: |
    acsccid is a PC/SC driver for Linux/Mac OS X and it supports ACS CCID smart card readers. This library provides a PC/SC IFD handler implementation and communicates with the readers through the PC/SC Lite resource manager (pcscd).
builddeps  :
    - pkgconfig(libusb-1.0)
    - pkgconfig(libpcsclite)
setup      : |
    %reconfigure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 src/92_pcscd_acsccid.rules $installdir%libdir%/udev/rules.d/92_pcscd_acsccid.rules
